cc charcode.c -o charcode
cc defines.c -o defines
cc float_overflow.c -o float_overflow
cc pizza.c -o pizza
cc praise1.c -o praise1
cc print1.c -o print1
cc print1_xlx.c -o print1_xlx
cc print2.c -o print2
cc printout.c -o printout
cc talkback.c -o talkback
cc toobig.c -o toobig
cc typesize.c -o typesize
